OPKitHelmetName: 'Cool Helmet Name'
OPKitChestplateName: 'Cool Chestplate Name'
OPKitLeggingsName: 'Cool Leggings Name'
OPKitBootsName: 'Cool Bewts Name'
OPKitSwordName: 'Cool Sword Name'
OPKitPickaxeName: 'Cool Pickaxe Name'
OPKitAxeName: 'Cool Axe Name'
OPKitShovelName: 'Cool Shovel Name'
OPKitShieldName: 'Cool Shield Name'