    name: CoreosEssentials
    version: 1.2
    api-version: 1.14
    main: com.gmail.corysaucer.Main
    commands:
      cereload:
        description: Reloads config
        usage: /cereload
        permission: coreo.reload
      heal:
        description: Heals sender
        usage: /heal
        permission: coreo.heal
      opkit:
        description: Gives OP kit
        usage: /opkit
        permission: coreo.opkit
      fly:
        description: Makes you fly or stop flying
        usage: /fly
        permission: coreo.fly
      gmc:
        description: Sets gamemode to creative
        usage: /gmc
        permission: coreo.gmc
      gms:
        description: Sets gamemode to survival
        usage: /gmc
        permission: coreo.gms
      feed:
        description: Feeds sender
        usage: /feed
        permission: coreo.feed
      tp:
        description: Teleports you to a player or teleports a player to another player
        usage: /tp <player> or /tp <player1> <player2>
        permission: coreo.tp
      tpall:
        description: Teleports all online players to your location
        usage: /tpall
        permission: coreo.tpall