    name: CoreosEssentials
    version: 1.0
    api-version: 1.14
    main: com.gmail.corysaucer.Main
    commands:
      cereload:
        description: Reloads config
        usage: reload
        permission: coreo.reload
      heal:
        description: Does something
        usage: /heal
        permission: coreo.heal
      opkit:
        description: Gives OP kit
        usage: opkit
        permission: coreo.opkit